---
- name: Sample IOS playbook to run show commands
  hosts: L09
  gather_facts: no

  tasks:
  - name: run show interface status
    cisco.ios.ios_command:
      commands: show interface status
    register: myinterfaces

  - name: display value of "myinterfaces" variable
    debug:
      var: myinterfaces["stdout_lines"][0]

  - name: run show users
    cisco.ios.ios_command:
      commands: show users
    register: myusers

  - name: display value of "myusers" variable
    debug:
      var: myusers["stdout_lines"][0]
